### ISSUE TITLE
what the cuda version of your test env?

### ISSUE THREAD

**Issue by Re3write** [mcahny/Deep-Video-Inpainting#13]
python3.6 and pytorch 0.4.0,but i still get this error when running the demo. I have installed the dependencies.

![image](https://user-images.githubusercontent.com/41424260/61454501-aa106a80-a993-11e9-9a59-011b5c97b81e.png)

**Comment by facetohard** [comment]
May be this issue #3  can help you. You can upgrade your pytorch to 1.1.0. The cuda version is 9.0
