### ISSUE TITLE
How long will it take to release your codes?

### ISSUE THREAD

**Issue by AziziShekoofeh** [mcahny/Deep-Video-Inpainting#2]
Thanks for the interesting paper. Since CVPR is already have finished, do you have an estimation for the release date? Many thanks again.

**Comment by mcahny** [comment]
Thank u for your interest!
Test code is now released. Yet not sure about the training code release.

**Comment by AziziShekoofeh** [comment]
@mcahny Thank you so much for the nice code. :)
