### ISSUE TITLE
Align-and-Attend Network Implementation 

### ISSUE THREAD

**Issue by AziziShekoofeh** [mcahny/Deep-Video-Inpainting#5]
Thanks again for the great code. I have a quick question about the "Align-and-Attend Network for Globally and Locally Coherent Video Inpainting" implementation. Do you or your group have any plan to release the codes related to this paper too? Thanks. :)

**Comment by mcahny** [comment]
Thanks for your interest!! The paper is under review for the moment, so hopefully, we d like to release the code upon the acceptance.

**Comment by AziziShekoofeh** [comment]
Thanks :)

**Comment by name8997** [comment]
I read this paper published in BMVC 2020 and it is very much awesome and interesting. 
So when is the code release scheduled? Thanks :)
