### ISSUE TITLE
Source codes of  Space-Time Cubic Puzzles

### ISSUE THREAD

**Issue by luodezhao** [mcahny/Deep-Video-Inpainting#6]
Hi, thanks for your sharing.  Do you have plan to release the implementation of "Self-Supervised Video Representation Learning with Space-Time Cubic Puzzles" ? 
Thanks !

**Comment by mcahny** [comment]
Yeah, hopefully within this year. Thanks for ur interest.

**Comment by ayushjain2699** [comment]
Hi, Thanks for your sharing. Have you uploaded the source code for "Self_Suoervised Video Representation Learning with Space-Time Cubic Puzzles"?
