### ISSUE TITLE
Could you please upload the training datasets and testing dataset?

### ISSUE THREAD

**Issue by ddghjikle** [mcahny/Deep-Video-Inpainting#7]
Thanks for your code. It's a fantastic work for video inpainting. However, datasets about the training and testing is hard to obtain by reading your paper. Therefore, could you please upload these related code or update these datasets? Thanks a lot.

**Comment by mcahny** [comment]
For the testing, you can download DAVIS dataset (https://davischallenge.org/), the folder trees are same as in "DAVIS_demo", so you can symlink to connect and test on more DAVIS samples.
For the training dataset, no clear estimation release, but still need time for the moment. Thanks for your interest.
