### ISSUE TITLE
a better inpainting method ?

### ISSUE THREAD

**Issue by DLSeed** [mcahny/Deep-Video-Inpainting#8]
《Deep Flow-Guided Video Inpainting》might generate better inpainting results，maybe you can check
https://github.com/nbei/Deep-Flow-Guided-Video-Inpainting  around July 14th when they release code :)

**Comment by mcahny** [comment]
That might be sacrificing the speed, running much slower than this one. A reasonable trade-off.

Ps. Sorry, but this is not a bulletin board for another work.

**Comment by mcahny** [comment]
That might be sacrificing the speed, running maybe slower (~8 mins per video, according to their paper). This one runs at much faster(~x10) rate, a reasonable trade-off.
