### ISSUE TITLE
Not an issue - question around inverse pixels

### ISSUE THREAD

**Issue by johndpope** [mcahny/Deep-Video-Inpainting#9]
in the  example the boy on bike is riding  and is then painted out - 
is it possible to get only those pixels / painting out of the bike? 
The parts that are ripped out / rotoscoped per frame / json coordinates?

**Comment by mcahny** [comment]
Well I not sure if I fully understand the question, but we use DAVIS video segmentation dataset for testing, and they provide full JPEG video frames with the corresponding binary mask sequences in png format (as in the DAVIS_demo folder). So to extract the foreground part out of the video, you can use these masks. Please check the dataset here. https://davischallenge.org/

**Comment by johndpope** [comment]
thanks
